services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: recsys_gvector-db
    env_file: .env
    restart: unless-stopped
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "$POSTGRES_PORT:5432"
    volumes:
      - ./backup/postgres:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
